### ISSUE TITLE
Cannot assign created jwt to environment variable

### ISSUE THREAD

**Issue by smonv** [mjamado/insomnia-plugin-jwt#3]
Everytime I assign jwt to a variable, it display weird syntax error

<img width="448" alt="Screen Shot 2019-08-27 at 21 24 42" src="https://user-images.githubusercontent.com/8962973/63779728-3a39bc00-c911-11e9-882d-96ac16fd4093.png">

**Comment by mjamado** [comment]
Confirmed. Introduced last night. I'm sorry. Will fix it tonight (GMT+1).

**Comment by mjamado** [comment]
Actually... No. Last night something was introduced that _may_ break until Insomnia is restarted. Not a bug, _per se_. At least not a bug with this plugin.

But this that you're seeing is something else. I see a similar error if I forget to put quotes around, but you did.

Can you share what are your settings inside the plugin?

**Comment by smonv** [comment]
@mjamado sorry for late reply

<img width="778" alt="Screen Shot 2019-08-29 at 02 40 00" src="https://user-images.githubusercontent.com/8962973/63887145-5703eb80-ca06-11e9-9739-8ec456a61822.png">

Inside plugin popup, everything working, and I can preview my jwt. But after I press Done and popup closed, the UI for manage environment start show reported error

**Comment by mjamado** [comment]
I've managed to reproduce it. It's because of the private claims. Will fix it.

**Comment by mjamado** [comment]
It *should* be fixed, can you test it and get back to me?

**Comment by smonv** [comment]
Thank for the fix. It working correctly now.
